COMPONENT_ADD_INCLUDEDIRS := src
COMPONENT_SRCDIRS := src
CXXFLAGS += -std=gnu++17
CPPFLAGS += \
    -DESPRESSIO_SOCKETS \
    -DESPRESSIO_SOCKETS_VERSION_MAJOR=0 \
    -DESPRESSIO_SOCKETS_VERSION_MINOR=2 \
    -DESPRESSIO_SOCKETS_VERSION_PATCH=0 \
    -DESPRESSIO_SOCKETS_VERSION_STRING=\"0.2.0\"
