name=ESPressio-Sockets
version=0.2.1
author=Flowduino
maintainer=Flowduino
sentence=Socket-based Event Transport and System Clock synchronization implementations for the ESPressio ecosystem.
paragraph=Provides UDP, TCP, TLS, WebSocket and MQTT Event transports plus opt-in ESPressio Timing System Clock synchronization over UDP, TCP, WebSocket and SNTP.
category=Communication
url=https://github.com/Flowduino/ESPressio-Sockets
architectures=esp32
includes=ESPressio_Sockets.hpp
depends=WebSockets,PubSubClient
